

OrdererOrgs:
  - Name: orderer
    Domain: orderer.maybe.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - localhost


PeerOrgs:
  - Name: org1
    Domain: org1.maybe.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: org2
    Domain: org2.maybe.com
    EnableNodeOUs: false
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

